feat/setup boilerplates
Today-budget-app/backend pull request #3
Opened 2024-03-08 08:33 UTC by FabricioBattaglia

Reworked boilerplates made during meeting.
Created routes that should be close to the actual routes that will be used
Organized folders

2024-03-12 16:48 UTC, victormoraesgs requested changes

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/transactionController.go
> +	//GORM create guide
```suggestion
```
No need for these comments

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/transactionController.go
> +	//get user
```suggestion
```

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/transactionController.go
> +	//respond
```suggestion
```

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/userController.go
> +
```suggestion
```

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/userController.go
> +	//get user
```suggestion
```

2024-03-12 16:48 UTC, victormoraesgs commented on controllers/userController.go
> +	//respond
```suggestion
```

2024-03-16 01:28 UTC, FabricioBattaglia commented
Followed suggestions, changes made.

2024-03-16 02:25 UTC, victormoraesgs approved these changes
LGTM

2024-03-16 03:02 UTC, merged